name: Build Multi-Architecture Image

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Build the Image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKER_HUB_USERNAME }}"/flask-example:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .